apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: ensemble
  namespace: seldon
spec:
  name: ensemble
  protocol: v2
  predictors:
    - name: ensemble
      graph:
        children: []
        implementation: "CUSTOM_IMPLEMENTATION"
        modelUri: s3://mlflow/0/testing/artifacts/cross_encoder_pyfunc #FIXME
        envSecretRefName: seldon-rclone-secret
        name: ensemble
      componentSpecs:
        - spec:
            containers:
            - name: ensemble
              env:
              - name: MLSERVER_MODELS_DIR
                value: "/mnt/models"
