apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
  namespace: seldon
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: <YOUR-VALUE> # FIXME
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: <YOUR-VALUE> # FIXME
  RCLONE_CONFIG_S3_ENDPOINT: <YOUR-VALUE> # FIXME
